services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: chatbot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wh0am177
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"

